name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: x86_64-linux
            host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: x86_64-windows
            host: windows-latest
            target: x86_64-pc-windows-gnu
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - shell: pwsh
        run: |
          cargo build --target=${{ matrix.target }} --release
          if (Test-Path ./target/${{ matrix.target }}/release/ci-playground.exe) {
            7z a ci-playground-${{ matrix.name }}.zip ./target/${{ matrix.target }}/release/ci-playground.exe
            Copy-Item ./target/${{ matrix.target }}/release/ci-playground.exe ./target/${{ matrix.target }}/release/ci-playground-${{ matrix.name }}.exe
          }
          elseif (Test-Path ./target/${{ matrix.target }}/release/ci-playground) {
            7z a ci-playground-${{ matrix.name }}.zip ./target/${{ matrix.target }}/release/ci-playground
            Copy-Item ./target/${{ matrix.target }}/release/ci-playground ./target/${{ matrix.target }}/release/ci-playground-${{ matrix.name }}
          }
      - uses: actions/upload-artifact@v7
        with:
          name: ci-playground-${{ matrix.name }}
          path: |
            target/${{ matrix.target }}/release/ci-playground-${{ matrix.name }}
            target/${{ matrix.target }}/release/ci-playground-${{ matrix.name }}.exe
            ci-playground-${{ matrix.name }}.zip

  github:
    needs: build
    permissions:
      contents: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - uses: actions/attest@v4
        with:
          subject-path: |
            ./ci-playground-*
            ./ci-playground-*.exe
            ./ci-playground-*.zip
      - run: gh release create ${{ github.ref_name }} ./ci-playground-* ./ci-playground-*.exe ./ci-playground-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
